// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFwfLuMCVKFXNaA7sYPhrz-W-AlZM6Yo',
    appId: '1:663884086142:web:b3f419717f780092c1d12f',
    messagingSenderId: '663884086142',
    projectId: 'systemmange-c6681',
    authDomain: 'systemmange-c6681.firebaseapp.com',
    storageBucket: 'systemmange-c6681.firebasestorage.app',
    measurementId: 'G-RMZ8TKWP9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GFUsPO58TvdmjOw9ne3R8gbjRCY6cOE',
    appId: '1:663884086142:android:9194038f9cc2271fc1d12f',
    messagingSenderId: '663884086142',
    projectId: 'systemmange-c6681',
    storageBucket: 'systemmange-c6681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZ375Je-YMmJ7wORhazw2AjZ5omUZavE',
    appId: '1:663884086142:ios:8f62a51189484b28c1d12f',
    messagingSenderId: '663884086142',
    projectId: 'systemmange-c6681',
    storageBucket: 'systemmange-c6681.firebasestorage.app',
    iosBundleId: 'com.example.systemManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuZ375Je-YMmJ7wORhazw2AjZ5omUZavE',
    appId: '1:663884086142:ios:8f62a51189484b28c1d12f',
    messagingSenderId: '663884086142',
    projectId: 'systemmange-c6681',
    storageBucket: 'systemmange-c6681.firebasestorage.app',
    iosBundleId: 'com.example.systemManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFwfLuMCVKFXNaA7sYPhrz-W-AlZM6Yo',
    appId: '1:663884086142:web:6ff820a5f77afd3fc1d12f',
    messagingSenderId: '663884086142',
    projectId: 'systemmange-c6681',
    authDomain: 'systemmange-c6681.firebaseapp.com',
    storageBucket: 'systemmange-c6681.firebasestorage.app',
    measurementId: 'G-J7T5JYP76Y',
  );
}
